### ISSUE TITLE
Pause Smooch swipe gesture

### ISSUE THREAD

**Issue by marcosgriselli** [smooch/smooch-helpkit-ios#10]
Hi, is there a way to pause the two finger swiping gesture and then restore it? Its conflicting with a part that also uses two finger swipes (Apple's ResearchKit).

**Comment by mspensieri** [comment]
You can enable / disable the gesture at runtime by doing the following:

```
[SmoochHelpKit settings].enableAppWideGesture = NO;

[SmoochHelpKit settings].enableAppWideGesture = YES;
```
