### ISSUE TITLE
[Cocoapods] [!] The 'Pods-MyProj' target has transitive dependencies that include static binaries: (.../Pods/Smooch/Smooch.framework)

### ISSUE THREAD

**Issue by hokster7** [smooch/smooch-helpkit-ios#4]
When I follow the instructions on the README, I get the above error.

See CocoaPods/CocoaPods#3267

**Comment by mspensieri** [comment]
I think this is because of the use of the `use_frameworks!` directive. It doesn't like that `SmoochHelpKit` declares a static library (i.e. `Smooch`) as a dependency.

A workaround for now would be to only use cocoapods for `Smooch`, and manually integrate `SmoochHelpKit`. Needs more investigation to see what we can do here though

**Comment by hokster7** [comment]
Thanks @mspensieri, I think that's the right diagnosis. In the age of Swift and frameworks for Cocoapods it'd be great if Smooch was compatible with `use_frameworks!`.  This is a real bit of resistance when upgrading from the `SupportKit` pod to `Smooch`+`SmoochHelpKit`!

EDIT: okay, I just saw your note on #59. Who's using iOS 7 these days?

**Comment by thediary** [comment]
Definitely think use_frameworks! support is a must these days! Could this be added soon?

**Comment by thediary** [comment]
Any update on this?

**Comment by hokster7** [comment]
@mspensieri I would suggest if the team can't be bothered to deal with Cocoapods, supporting Carthage is a good option.  Carthage supports downloading binary releases and how it's all linked is up to the user.

**Comment by mspensieri** [comment]
@thediary @fatuhoku Sorry for the slow movement on this :(, hoping to be able to tackle it soon

**Comment by mspensieri** [comment]
This issue should be resolved with the release of smooch-ios [v4.0.0](https://github.com/smooch/smooch-ios/releases/tag/4.0.0), but requires a deployment target of at least iOS 8.0

**Comment by gemmakbarlow** [comment]
Fantastic, thanks Mike.
